name: Update Profile

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  profile:
    runs-on: ubuntu-latest

    steps:

      - name: GitHub Activity
        uses: lowlighter/metrics@latest
        with:
          user: OmarMeshref
          token: ${{ secrets.METRICS_TOKEN }}

          filename: assets/omar-activity.svg
          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year


      - name: Programming Languages
        uses: lowlighter/metrics@latest
        with:
          user: OmarMeshref
          token: ${{ secrets.METRICS_TOKEN }}

          filename: assets/omar-stack.svg
          base: ""

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes

          commits_authoring: >-
            OmarMeshref,
            Omar2002A,
            mushrefo19@gmail.com

          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 6
          plugin_languages_threshold: 2%
          plugin_languages_analysis_timeout: 30


      - name: Tech Interests
        uses: lowlighter/metrics@latest
        with:
          user: OmarMeshref
          token: NOT_NEEDED

          filename: assets/omar-interests.svg
          base: ""

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: starred
          plugin_topics_limit: 12


      - name: Check PageSpeed secret
        env:
          PAGESPEED_TOKEN: ${{ secrets.PAGESPEED_TOKEN }}
        run: |
          if [ -z "$PAGESPEED_TOKEN" ]; then
            echo "PAGESPEED_TOKEN is EMPTY"
            exit 1
          else
            echo "PAGESPEED_TOKEN is available"
          fi

      - name: Portfolio Health
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED

          filename: assets/portfolio-health.svg
          base: ""

          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://omarmeshref.github.io/Portofolio/